// Create an account
POST http://localhost:8080/register
Accept: application/xml
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiZXhwIjoxNjE3MjA1MzczfQ.nsFca2XDa3EFVRdn4KOK_TkVLUGdWYT9oQfFb22zxkg

<user>
    <name>test2</name>
    <password>test2</password>
</user>

###

// Login
// Sans sécurité
POST http://localhost:8080/login
Accept: application/xml
Content-Type: application/xml

<user>
    <name>test</name>
    <password>test</password>
</user>

###

// Avec sécurité (mode user)
POST http://localhost:8080/login?username=test&password=test
Accept: application/xml

###

// Avec sécurité (mode admin)
POST http://localhost:8080/login?username=admin&password=admin
Accept: application/xml

###

//Get all videos
GET http://localhost:8080/video
Accept: application/xml

###

//Get user details
GET http://localhost:8080/user/test
Accept: application/xml

###

//Get user's videos
GET http://localhost:8080/user/test/video
Accept: application/xml

###

//Add a video
POST http://localhost:8080/user/test/video
Accept: application/xml
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTYxNzIwNDg0NX0.uI0jJIq8oH6eECLICtABc02QGbqGzn0fmF-7UZnADqI


<video>
    <url>https://www.youtube.com/watch?v=10h15BIygNI</url>
    <title>Examen Web service </title>
    <description>Debrief du sujet d’entraînement à l'examen de Webservices
</description>
</video>

###

//Get user's playlists
GET http://localhost:8080/user/test/playlist
Accept: application/xml

###

//Create a new playlist
POST http://localhost:8080/user/test/playlist/new/testPlaylist
Content-Type: application/xml
Accept: application/xml

###

//Modify a playlist
PUT http://localhost:8080/user/test/playlist/0
Content-Type: application/xml

<playlist>
    <videos>
        <video>
            <url>https://www.youtube.com/watch?v=_WzAA_HyP6c</url>
            <title>Installer Java FX </title>
            <description>Tuto JFx - Installer et configurer JavaFX sous IntelliJ - génération d'un projet par Archetype Maven
</description>
        </video>
    </videos>
</playlist>

###

//Delete playlist
DELETE http://localhost:8080/user/test/playlist/0
